### ISSUE TITLE
Rmarkdown

### ISSUE THREAD

**Issue by ACCRETEAOML** [sformel/CRANG#1]
Error` in loadNamespace(name) : there is no package called ‘rmarkdown’

Error above when code is run. Can't find an rmarkdown package through R studio, is that something extra needed?

**Comment by sformel** [comment]
hmm, that's unexpected.  rmarkdown should come packaged with Rstudio.  But see [this discussion](https://stackoverflow.com/questions/24733383/r-within-rstudio-cannot-find-rmarkdown-package).  I can help you troubleshoot on Thursday.  

In the meantime if you can't get it figured out you can copy and paste the chunks of code from the [rmarkdown document](https://github.com/sformel/CRANG/blob/main/CRANG_pH_O2.Rmd) into a regular r script and run it.

a code chunk is the portion after the ```{r, blah blah } section and before the second \`\`\`
